# ************************************************************************** #
#                                                                            #
#                                                        :::      ::::::::   #
#   docker-compose.yml                                   :+:      :+:    :+:   #
#                                                    +:+ +:+         +:+     #
#   By: ynieto-s <ynieto-s@student.42.fr>            +#+  +:+       +#+        #
#                                                +#+#+#+#+#+   +#+           #
#   Created: 2026/08/15 16:32:00 by ynieto-s           #+#    #+#             #
#   Updated: 2026/08/15 16:38:00 by ynieto-s           ###   ########.fr       #
#                                                                            #
# ************************************************************************** #

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
      - credentials
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
